# Generated by Django 4.0.3 on 2022-04-07 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='acnt_monthdays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_fromdate', models.DateField(blank=True, null=True)),
                ('month_todate', models.DateField(blank=True, null=True)),
                ('month_workingdays', models.IntegerField()),
                ('month_holidays', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='test_status',
            old_name='files',
            new_name='json',
        ),
        migrations.AddField(
            model_name='branch_registration',
            name='email',
            field=models.EmailField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='branch_registration',
            name='logo',
            field=models.FileField(blank=True, default='', null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='branch_registration',
            name='mobile',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='branch',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='branch', to='base_app.branch_registration'),
        ),
        migrations.AddField(
            model_name='project_taskassign',
            name='delay',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='test_status',
            name='json_testerscreenshot',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user_registration',
            name='confirm_salary',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user_registration',
            name='confirm_salary_status',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AddField(
            model_name='user_registration',
            name='payment_amount_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user_registration',
            name='payment_file_downlod',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='user_registration',
            name='salary_pending',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user_registration',
            name='salary_status',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='user_registration',
            name='total_amount',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='acntspayslip',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dept', to='base_app.department'),
        ),
        migrations.AlterField(
            model_name='acntspayslip',
            name='designation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='desic', to='base_app.designation'),
        ),
        migrations.AlterField(
            model_name='acntspayslip',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='base_app.user_registration'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendanceuser', to='base_app.user_registration'),
        ),
        migrations.AlterField(
            model_name='department',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departmentbranch', to='base_app.branch_registration'),
        ),
        migrations.AlterField(
            model_name='designation',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='designationbranch', to='base_app.branch_registration'),
        ),
        migrations.AlterField(
            model_name='designation',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departmentbranch', to='base_app.department'),
        ),
        migrations.AlterField(
            model_name='extracurricular',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extracurricularuser', to='base_app.user_registration'),
        ),
        migrations.AlterField(
            model_name='internship',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internshipbranch', to='base_app.branch_registration'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leaveuser', to='base_app.user_registration'),
        ),
        migrations.AlterField(
            model_name='paymentlist',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userpay', to='base_app.user_registration'),
        ),
        migrations.AlterField(
            model_name='project',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projectdepartment', to='base_app.department'),
        ),
        migrations.AlterField(
            model_name='project',
            name='designation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projectdesignation', to='base_app.designation'),
        ),
        migrations.AlterField(
            model_name='project',
            name='projectmanager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projectuser', to='base_app.user_registration'),
        ),
        migrations.AlterField(
            model_name='project',
            name='tester',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projecttester', to='base_app.user_registration'),
        ),
        migrations.AlterField(
            model_name='project_taskassign',
            name='developer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_taskassignuser', to='base_app.user_registration'),
        ),
        migrations.AlterField(
            model_name='project_taskassign',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_taskassignproject', to='base_app.project'),
        ),
        migrations.AlterField(
            model_name='project_taskassign',
            name='tester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_taskassign_tester', to='base_app.user_registration'),
        ),
        migrations.AlterField(
            model_name='project_taskassign',
            name='tl',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_taskassigntl', to='base_app.user_registration'),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qualificationuser', to='base_app.user_registration'),
        ),
        migrations.AlterField(
            model_name='reported_issue',
            name='reported_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_issuereported_to', to='base_app.user_registration'),
        ),
        migrations.AlterField(
            model_name='reported_issue',
            name='reporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_issuereporter', to='base_app.user_registration'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taskdepartment', to='base_app.department'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='designation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taskdesignation', to='base_app.designation'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taskuser', to='base_app.user_registration'),
        ),
        migrations.AlterField(
            model_name='test_status',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_statusproject', to='base_app.project'),
        ),
        migrations.AlterField(
            model_name='test_status',
            name='subtask',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_statustaskname', to='base_app.project_taskassign'),
        ),
        migrations.AlterField(
            model_name='test_status',
            name='taskname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_statustaskname', to='base_app.user_registration'),
        ),
        migrations.AlterField(
            model_name='test_status',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_statususer', to='base_app.user_registration'),
        ),
        migrations.AlterField(
            model_name='tester_status',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tester_statusproject', to='base_app.project'),
        ),
        migrations.AlterField(
            model_name='tester_status',
            name='subtask',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tester_statussubtask', to='base_app.project_taskassign'),
        ),
        migrations.AlterField(
            model_name='tester_status',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tester_statustask', to='base_app.project_taskassign'),
        ),
        migrations.AlterField(
            model_name='tester_status',
            name='tester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tester_statustester', to='base_app.user_registration'),
        ),
        migrations.AlterField(
            model_name='tester_status',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tester_statususer', to='base_app.user_registration'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='trainee',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topictrainee', to='base_app.user_registration'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topictrainer', to='base_app.user_registration'),
        ),
        migrations.AlterField(
            model_name='trainer_task',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainer_task_trainee', to='base_app.user_registration'),
        ),
        migrations.AlterField(
            model_name='user_registration',
            name='account_no',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user_registration',
            name='bank_name',
            field=models.CharField(blank=True, default='', max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='user_registration',
            name='branch',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userregistrationbranch', to='base_app.branch_registration'),
        ),
        migrations.AlterField(
            model_name='user_registration',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userregistrationdepartment', to='base_app.department'),
        ),
        migrations.AlterField(
            model_name='user_registration',
            name='designation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userregistrationdesignation', to='base_app.designation'),
        ),
        migrations.AlterField(
            model_name='user_registration',
            name='enddate',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_registration',
            name='joiningdate',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_registration',
            name='startdate',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_registration',
            name='status',
            field=models.CharField(default='active', max_length=240, null=True),
        ),
        migrations.CreateModel(
            name='previousTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pstatus', models.CharField(max_length=200)),
                ('teamname', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teamname', to='base_app.create_team')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user1', to='base_app.user_registration')),
            ],
        ),
    ]
